### ISSUE TITLE
How to use code

### ISSUE THREAD

**Issue by 9shengjiu** [helloDestroyerOfWorlds/propeller_design_tools#3]
Hello, I want to know about this code, but I downloaded it and can't use it on python. It always makes mistakes, so I want to ask if there is a use guide

**Comment by helloDestroyerOfWorlds** [comment]
nope, just the readme file.  You could tell me more about the mistakes though and I could try to help further?

**Comment by helloDestroyerOfWorlds** [comment]
Have you been able to make any headway?  There's a requirements file as well, which contains all the things you must pip install first in order for it to run in python without erroring (sorry... I'll fix this later... at the time of writing this package I didn't know how to make things automatically pip install when people pip install this package).

**Comment by helloDestroyerOfWorlds** [comment]
If you don't mind I'm going to close this issue.  I just figured out how to have it pip install all its own dependencies when you "pip install propeller_design_tools" which should fix this issue for you, assuming you follow the readme.  The next update will incorporate that feature.
